# MA_Project_Practice 2/docker-compose.yml
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306" # Map host port 3306 to container port 3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # Set the root password for MySQL container
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Run init script on start
    networks:
      - fraud-network
    healthcheck:
      # Corrected: Use the password set in environment (1234)
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  eureka-server:
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - fraud-network

  api-gateway:
    image: api-gateway:latest
    ports:
      - "3001:3001"
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - fraud-network
    restart: on-failure

  user-service:
    image: userservice:latest
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      # Corrected: Password must match MYSQL_ROOT_PASSWORD
      SPRING_DATASOURCE_PASSWORD: 1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - fraud-network
    restart: on-failure

  transaction-service:
    image: transactionservice:latest
    ports:
      - "8087:8087"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      fraud-detect-service:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/transactiondb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      # Corrected: Password must match MYSQL_ROOT_PASSWORD
      SPRING_DATASOURCE_PASSWORD: 1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - fraud-network
    restart: on-failure

  notification-service:
    image: notificationservice:latest
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/notificationdb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      # Correct: Matches MYSQL_ROOT_PASSWORD
      SPRING_DATASOURCE_PASSWORD: 1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - fraud-network
    restart: on-failure

  fraud-detect-service:
    image: frauddetectservice:latest
    ports:
      - "8089:8089"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/frauddetectiondb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      # Correct: Matches MYSQL_ROOT_PASSWORD
      SPRING_DATASOURCE_PASSWORD: 1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - fraud-network
    restart: on-failure

volumes:
  mysql_data:

networks:
  fraud-network:
    driver: bridge