apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detect-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detect-service
  template:
    metadata:
      labels:
        app: fraud-detect-service
    spec:
      containers:
        - name: fraud-detect-service
          image: 70322000079/frauddetectservice:latest
          ports:
            - containerPort: 8089
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
